# Generated by Django 2.1.3 on 2018-11-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181117_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('In progress', 'In progress'), ('Received', 'Received')], default='Received', max_length=120),
        ),
    ]
