# Generated by Django 2.1.3 on 2018-11-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181118_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In progress', 'In progress'), ('Paid', 'Paid')], default='Received', max_length=120),
        ),
    ]
