# Generated by Django 2.1.3 on 2018-12-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181120_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
