# Generated by Django 2.1.3 on 2018-12-27 21:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181227_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.image_upload_path),
        ),
    ]
