# Generated by Django 2.1.3 on 2018-12-27 21:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tourcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(upload_to=app.models.image_upload_path),
        ),
    ]
