# Generated by Django 2.1.3 on 2018-12-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181227_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='short_description',
            field=models.TextField(),
        ),
    ]
