# Generated by Django 2.1.3 on 2018-12-27 22:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181227_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='icon',
            field=models.ImageField(blank=True, upload_to=app.models.icon_upload_path),
        ),
    ]
